#!/bin/bash
set -o pipefail
packagename=$1

if [ $packagename == "" ]; then
  echo packagename at 1st argument required.
  exit 1
fi

mkdir -p packages/$packagename
cp -R template/ packages/$packagename/
